idf_component_register(
    SRCS "main.c"
         "tarot_app.c"
         "tarot_deck.c"
         "tarot_engine.c"
         "tarot_nav.c"
         "tarot_emblem_math.c"
         "tarot_theme.c"
         "tarot_emblem.c"
         "tarot_art.c"
         "tarot_pages_home.c"
         "tarot_pages_cast.c"
         "tarot_pages_card.c"
         "${CMAKE_CURRENT_LIST_DIR}/../assets/fonts/tarot_font_16.c"
         "${CMAKE_CURRENT_LIST_DIR}/../assets/fonts/tarot_font_24.c"
         "${CMAKE_CURRENT_LIST_DIR}/../assets/fonts/tarot_font_48.c"
         "${CMAKE_CURRENT_LIST_DIR}/../assets/images/tarot_art_img.c"
         "${CMAKE_CURRENT_LIST_DIR}/../assets/images/tarot_art_mini.c"
    INCLUDE_DIRS "." "../assets/images"
    REQUIRES bsp esp_hw_support
)
