// assets/images/tarot_art.h - embedded tarot card artwork (generated).
// Generated by tools/gen_tarot_art.py; do not edit by hand.
// Source: Rider-Waite-Smith tarot deck (1909, Pamela Colman Smith), public domain; digitation via github.com/searge/tarot
// Two resolutions: full 120x180 (card page, single reveal) and
// mini 64x96 (three-card reveal slots); LVGL renders each 1:1.
// Card id matches main/tarot_deck.h.
#pragma once

#include "lvgl.h"

#ifdef __cplusplus
extern "C" {
#endif

#define TAROT_ART_COUNT 78
#define TAROT_ART_W 120
#define TAROT_ART_H 180
#define TAROT_ART_MINI_W 64
#define TAROT_ART_MINI_H 96

extern const lv_image_dsc_t tarot_card_images[TAROT_ART_COUNT];
extern const lv_image_dsc_t tarot_card_mini_images[TAROT_ART_COUNT];

#ifdef __cplusplus
}
#endif
