#!/usr/bin/env python3
"""Generate the embedded tarot card artwork for the firmware.

Converts the 78 public-domain Rider-Waite-Smith (1909, Pamela Colman Smith)
card scans into RGB565 arrays compiled into the application, at two
resolutions: full 120x180 (card page and single-card reveal) and mini 64x96
(three-card reveal slots). LVGL cannot scale images on this no-PSRAM board
(transform would need an offscreen layer), so each display size renders a
1:1 set.

Card id mapping (must match main/tarot_deck.c):
  id   0..21  major arcana     -> maj00.jpg .. maj21.jpg
  id  22..35  wands 1..14      -> wands01.jpg .. wands14.jpg
  id  36..49  cups 1..14       -> cups01.jpg .. cups14.jpg
  id  50..63  swords 1..14     -> swords01.jpg .. swords14.jpg
  id  64..77  pentacles 1..14  -> pents01.jpg .. pents14.jpg

Usage:
  python tools/gen_tarot_art.py           # convert build/rws-src/*.jpg (already fetched)
  python tools/gen_tarot_art.py --fetch   # download the scans first (needs curl)
  python tools/gen_tarot_art.py --check   # verify committed output is up to date

Output (committed, deterministic):
  assets/images/tarot_art.h       shared header (both descriptor arrays)
  assets/images/tarot_art_img.c   full set, 120x180
  assets/images/tarot_art_mini.c  mini set, 64x96
"""

from __future__ import annotations

import argparse
import subprocess
from pathlib import Path

REPO = Path(__file__).resolve().parent.parent
SRC_DIR = REPO / "build" / "rws-src"
OUT_H = REPO / "assets" / "images" / "tarot_art.h"
OUT_FULL = REPO / "assets" / "images" / "tarot_art_img.c"
OUT_MINI = REPO / "assets" / "images" / "tarot_art_mini.c"

FULL_W, FULL_H = 120, 180
MINI_W, MINI_H = 64, 96
SOURCE_URL = "https://raw.githubusercontent.com/searge/tarot/master/assets/img/big"
PROVENANCE = ("Rider-Waite-Smith tarot deck (1909, Pamela Colman Smith), "
              "public domain; digitation via github.com/searge/tarot")

CARD_WANDS = 22
CARD_CUPS = 36
CARD_SWORDS = 50
CARD_PENTACLES = 64


def card_sources() -> list[tuple[int, str]]:
    """78 (card_id, filename) pairs in deck order."""
    pairs = [(i, "maj%02d.jpg" % i) for i in range(22)]
    for base, stem in ((CARD_WANDS, "wands"), (CARD_CUPS, "cups"),
                       (CARD_SWORDS, "swords"), (CARD_PENTACLES, "pents")):
        pairs += [(base + i - 1, "%s%02d.jpg" % (stem, i)) for i in range(1, 15)]
    return pairs


def fetch() -> None:
    SRC_DIR.mkdir(parents=True, exist_ok=True)
    failed = []
    for _, name in card_sources():
        dest = SRC_DIR / name
        if dest.is_file() and dest.stat().st_size > 1000 \
                and dest.read_bytes()[:3] == b"\xff\xd8\xff":
            continue
        url = f"{SOURCE_URL}/{name}"
        result = subprocess.run(
            ["curl", "-sL", "--max-time", "60", "-A", "Mozilla/5.0",
             "-o", str(dest), url])
        ok = result.returncode == 0 and dest.read_bytes()[:3] == b"\xff\xd8\xff"
        print(("ok  " if ok else "FAIL") + " " + name)
        if not ok:
            failed.append(name)
    if failed:
        raise SystemExit("download failed: " + ", ".join(failed))


def rgb565_value(r: int, g: int, b: int) -> int:
    return ((r >> 3) << 11) | ((g >> 2) << 5) | (b >> 3)


def convert_cards(width: int, height: int) -> list[tuple[int, str, bytes]]:
    try:
        from PIL import Image
    except ImportError:
        raise SystemExit("Pillow is required: python -m pip install pillow")

    # 源图 350x600(约 7:12);裁掉顶部 10px、底部 65px:底部窄条是扫描件
    # 自带的英文牌名,屏上不可读,牌名由应用的中文字幕承担。
    CROP_TOP, CROP_BOTTOM = 10, 65
    out = []
    for card_id, name in card_sources():
        path = SRC_DIR / name
        if not path.is_file():
            raise SystemExit(f"missing source image: {path}")
        im = Image.open(path).convert("RGB")
        im = im.crop((0, CROP_TOP, im.width, im.height - CROP_BOTTOM))
        target_ratio = width / height
        w, h = im.size
        if abs(w / h - target_ratio) > 0.01:
            crop_h = round(w / target_ratio)
            top = (h - crop_h) // 2
            im = im.crop((0, top, w, top + crop_h))
        im = im.resize((width, height), Image.LANCZOS)
        pixels = im.tobytes()
        words = bytearray()
        for i in range(0, len(pixels), 3):
            value = rgb565_value(pixels[i], pixels[i + 1], pixels[i + 2])
            words += value.to_bytes(2, "little")
        out.append((card_id, name, bytes(words)))
    return out


def c_array_name(prefix: str, card_id: int) -> str:
    return f"{prefix}_{card_id:02d}"


def render(width: int, height: int, prefix: str, descriptor: str,
           source_name: str) -> str:
    body = [f"""// assets/images/{source_name} - embedded tarot card artwork (generated).
// Generated by tools/gen_tarot_art.py; do not edit by hand.
// Source: {PROVENANCE}
// 78 cards, {width}x{height} RGB565.
#include "tarot_art.h"

"""]
    cards = convert_cards(width, height)
    for card_id, name, data in cards:
        body.append(f"// card {card_id}: {name}\n")
        array = c_array_name(prefix, card_id)
        body.append(f"static const uint16_t {array}[{width * height}] = {{\n")
        for i in range(0, len(data), 2):
            value = int.from_bytes(data[i:i + 2], "little")
            body.append("0x%04X," % value)
            if (i // 2) % 12 == 11:
                body.append("\n")
        body.append("\n};\n\n")

    body.append(f"const lv_image_dsc_t {descriptor}[TAROT_ART_COUNT] = {{\n")
    for card_id, _, _ in cards:
        array = c_array_name(prefix, card_id)
        body.append(
            f"    [{card_id}] = {{\n"
            f"        .header.magic = LV_IMAGE_HEADER_MAGIC,\n"
            f"        .header.cf = LV_COLOR_FORMAT_RGB565,\n"
            f"        .header.w = {width},\n"
            f"        .header.h = {height},\n"
            f"        .header.stride = {width * 2},\n"
            f"        .data = (const uint8_t *){array},\n"
            f"        .data_size = sizeof({array}),\n"
            f"    }},\n")
    body.append("};\n")
    return "".join(body)


def shared_header() -> str:
    return f"""// assets/images/tarot_art.h - embedded tarot card artwork (generated).
// Generated by tools/gen_tarot_art.py; do not edit by hand.
// Source: {PROVENANCE}
// Two resolutions: full {FULL_W}x{FULL_H} (card page, single reveal) and
// mini {MINI_W}x{MINI_H} (three-card reveal slots); LVGL renders each 1:1.
// Card id matches main/tarot_deck.h.
#pragma once

#include "lvgl.h"

#ifdef __cplusplus
extern "C" {{
#endif

#define TAROT_ART_COUNT 78
#define TAROT_ART_W {FULL_W}
#define TAROT_ART_H {FULL_H}
#define TAROT_ART_MINI_W {MINI_W}
#define TAROT_ART_MINI_H {MINI_H}

extern const lv_image_dsc_t tarot_card_images[TAROT_ART_COUNT];
extern const lv_image_dsc_t tarot_card_mini_images[TAROT_ART_COUNT];

#ifdef __cplusplus
}}
#endif
"""


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--fetch", action="store_true",
                        help="download the source scans first")
    parser.add_argument("--check", action="store_true",
                        help="verify committed output is up to date")
    args = parser.parse_args()
    if args.fetch:
        fetch()
    header = shared_header()
    full_body = render(FULL_W, FULL_H, "k_tarot_card", "tarot_card_images",
                       "tarot_art_img.c")
    mini_body = render(MINI_W, MINI_H, "k_tarot_card_mini",
                       "tarot_card_mini_images", "tarot_art_mini.c")
    if args.check:
        for path, expected in ((OUT_H, header), (OUT_FULL, full_body),
                               (OUT_MINI, mini_body)):
            if path.read_text(encoding="utf-8") != expected:
                raise SystemExit(
                    f"{path.relative_to(REPO)} is out of date; run "
                    "python tools/gen_tarot_art.py [--fetch] and commit")
        print("tarot art: committed output is up to date")
        return
    OUT_H.parent.mkdir(parents=True, exist_ok=True)
    OUT_H.write_text(header, encoding="utf-8")
    OUT_FULL.write_text(full_body, encoding="utf-8")
    OUT_MINI.write_text(mini_body, encoding="utf-8")
    print(f"wrote {OUT_H.relative_to(REPO)}, "
          f"{OUT_FULL.relative_to(REPO)} ({OUT_FULL.stat().st_size // 1024} KiB), "
          f"{OUT_MINI.relative_to(REPO)} ({OUT_MINI.stat().st_size // 1024} KiB)")


if __name__ == "__main__":
    main()
